### PR TITLE
Minor clarification of ReadMe

### PR DESCRIPTION
**Pull request by TPS**
@AdGuardTeam When quoting the ReadMe for https://github.com/AdguardTeam/AdguardForAndroid/issues/861#issuecomment-255901889, I happened to see the source, & realized, maybe, you all were attempting something more like this.  I happened to find a HTTP-link, too, though (I think) AdGuard.com went HTTPS-only some point within the last year.

What d'y'all think?

### CODE REVIEW

**Comment by ameshkov** [comment]
I've also added a privacy policy link there.

**Comment by war59312** [comment]
I take it you did NOT mean to have "TL;DR" as in "Too long; didn't read" in there:

> Privacy policy: https://adguard.com/en/privacy.html#android (TL;DR: we send information necessary for a license check).

Perhaps you meant something more along the lines of:

> Privacy policy: https://adguard.com/en/privacy.html#android (Note: AdGuard sends required limited information necessary for a license check to AdGuard.com.)

**Comment by TPS** [comment]
@war59312 I figure `TL;DR` is ok for the intended audience who glazes over w/ legalese.  I mean, e.g., as important as the GPLs are, what %age of folks have actually read them?

**Comment by ameshkov** [comment]
@war59312

I often see `tl;dr` used to mark a short description, for those who are not fond of reading more than a few sentences. Am I wrong?

Changed it to `Briefly, AdGuard sends required limited information necessary for a license check `

**Comment by war59312** [comment]
@TPS, I do agree with that, but not everyone knows the shorthand. I had to google it. lol

@ameshkov That's better.

Always best to spell it out I think.

So thanks.

But yes I do see it from time to time now that I think about it, as I never really took the time to see what it meant.

**Pull request merged**
